# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pirate Party UK
email: webteam@pirateparty.org.uk
description: Website for the UK Pirate Party, a centrist party focusing on Digital Rights and Freedom.
keywords: Pirate, Pirate Party, Party, PPUK, PP, United Kingdom, Politics, Digital Rights, Digital Freedom.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pirateparty.org.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate_path: "/news/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor

sass:
    style: compressed

permalink: /article/:title.html
collections:
  policy:
    output: true
    permalink: /policy/:path/

defaults:   # defaults values for collection scope

title-page:
  big:
    foto: /assets/img/miscellaneous/you-can.png
    alt: policy
    url: policy
  left-top:
    text: Welcome
    url:
    icon: fa fa-map-signs
  # right-top:
  #  text: Hi there
  #  url: 
  #  icon: fa fa-users
  # left-bottom:
  #  text: Hello
  #  url: 
  #  icon: fa fa-gift u-rotate-5 fa-5x u-rotate-345
  right-bottom:
    text: Our Beliefs
    url: policy
    icon: fa fa-newspaper-o u-rotate-345

emptyArray: []
