# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pirate Party UK
email: webteam@pirateparty.org.uk
description: Website for the UK Pirate Party, a centrist party focusing on Digital Rights and Freedom.
keywords: Pirate, Pirate Party, Party, PPUK, PP, United Kingdom, Politics, Digital Rights, Digital Freedom.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pirateparty.org.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate_path: "/news/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor

sass:
    style: compressed

permalink: /article/:title.html
collections:
  policy:
    output: true
    permalink: /policy/:path/

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_policy"
    values:
      layout: "page"
      rbar: "program"

emptyArray: []
